### ISSUE TITLE
Fun lab for data viz

### ISSUE THREAD

**Issue by apreshill** [uo-datasci-specialization/c2-communicate_transform_data#5]
Did this on Monday:

https://apreshill.github.io/data-vis-labs-2018/slides/11-slides.html#1

For @datalorax: I made this interactive by 

1. Printing out handouts with each dataset (unnamed). I added a colored dot at the top for each of them. 

1. For every plot when it appeared on the screen, I had them discuss in pairs (1-2 minutes) to pick which dataset was used to make that plot. 

1. I polled by calling out the colors, then had someone who picked it right say why. I thought it was a fun lab! 

Some notes:

- Not every plot is "good"- in class we discussed what made them good, what was hard to interpret, what plot was good for exploratory vs explanatory goals, further tweaks that might improve it, etc.
- Our discussion focused on how starting from tidy data helps with most visualizations, and makes it easy to reshape to get the vis you want.

**Comment by datalorax** [comment]
Thanks Alison! This looks awesome!
